### PR TITLE
Adding Ignis

### PR DESCRIPTION
**Pull request by ereboucas**
https://app.cod.ignisfit.com, score: 0.93
is-on-https:1, weight(2), 2
redirects-http:1, weight(2), 2
service-worker:1, weight(1), 1
works-offline:1, weight(5), 5
viewport:1, weight(2), 2
without-javascript:0, weight(1), 0
load-fast-enough-for-pwa:1, weight(7), 7
installable-manifest:1, weight(2), 2
apple-touch-icon:1, weight(1), 1
splash-screen:1, weight(1), 1
themed-omnibox:0, weight(1), 0
content-width:1, weight(1), 1
offline-start-url:1, weight(1), 1
pwa-cross-browser:null, weight(0), 0
pwa-page-transitions:null, weight(0), 0
pwa-each-page-has-url:null, weight(0), 0

### CODE REVIEW

**Review by cmilfont — CHANGES_REQUESTED** [review]
@ereboucas acessei aqui e o certificado está inválido, é isso mesmo?

certificado

**Comment by ereboucas** [comment]
Milfont, não aparece isso pra mim. Usamos o Let's Encrypt e o certificado está válido até 28/10/2019

Selection_048

**Comment by cmilfont** [comment]
De qualquer forma precisa resolver o conflito

**Comment by ereboucas** [comment]
Conflito resolvido

**Review by cmilfont — APPROVED** [review]

**Pull request merged**
